es_host: localhost         # Elasticsearch host, default is localhost
es_port: 9201              # Elasticsearch port, default is 9201

# Either prov_code or geog_id is required for a normal run.
# Uncomment one of the following for the desired mode.
# prov_code: "PE"            # must be provided if geog_id is not provided or in recovery rerun mode
geog_id: "g30_f85qwk5e"  # Optional geographic ID, in normal run, if provided prov_code will be ignored, pe_montague

lang: en                   # Language, default is en
log_level: ERROR           # Logging Level, default is ERROR

# Recovery mode settings (used with --rerun)
# Uncomment and set appropriately when in recovery mode.
# run_num: 1               # The rerun number, only relevant if --rerun is true
# gpt_backup_version: "202312" # The version of records in archiver_file for recovery

#archiver_file: ./archive_rewrites.txt     # Filepath to the archiver file
archiver_file: /Users/kechan/tmp/archive_rewrites.txt     # for local testing

